### PR TITLE
dice command

### PR DESCRIPTION
**Pull request by VijayStroup**

### CODE REVIEW

**Review by suneettipirneni — APPROVED** [review]

**Comment by rob-3** [comment]
Can we come up with a better name than `nToS` for the record?

**Comment by rob-3** [comment]
Also maybe avoid using `number` for a variable name since it is also a type.

**Comment by VijayStroup** [comment]
> Also maybe avoid using `number` for a variable name since it is also a type. How about `n` or `randomNumber`?
> 
> Otherwise this looks good to merge.

True forgot about this one...

**Comment by rob-3** [comment]
> > Also maybe avoid using `number` for a variable name since it is also a type. How about `n` or `randomNumber`?
> > Otherwise this looks good to merge.
> 
> True forgot about this one...
> but nToS was good 😡

It was a bit cryptic for my taste. This ain't C where we have to worry about saving a byte here and a byte there.

**Pull request merged**
