### PR TITLE
Add crumbl command

### PR DESCRIPTION
**Pull request by rob-3**
Simple port of https://github.com/rob-3/crumblbot/

### CODE REVIEW

**Comment by Armintron** [comment]
Could we use buttons for pagination rather than posting all cookies at once?

**Comment by rob-3** [comment]
There's only every 4-5 cookies, so I feel like pagination just needlessly slows things down. Are you worried it is too much embed spam?

**Comment by Armintron** [comment]
I just think it's cleaner. I really like lions crumbl plugin

**Comment by rob-3** [comment]
Hmm ok well I could manually build the pagination but it would be nice to have a helper for pagination where you just pass in the array of embeds and it sets up the buttons and editing for you.

**Comment by suneettipirneni** [comment]
> I just think it's cleaner. I really like lions crumbl plugin

I agree, especially on mobile, sometimes 4-5 embeds can take up the entire chat view. Also buttons makes pagination more user friendly IMO.

**Review by suneettipirneni — APPROVED** [review]

**Pull request merged**
